services:
  app-login:
    build: app-login
    mem_limit: 512m
    ports:
      - "8070:8070"
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=contrase√±a
      - PRIVATE_KEY=b9e09af3c4942c8667f5cee3828d2c2d87ad56dc422d4f8afce3913ef77a5e4d
      - USER_GENERATOR=PROJECT
      - DB_URL=jdbc:postgresql://login_db:5432/login
      - DB_USER=pg 
      - DB_PASSWORD=contrasecontrase
    restart: always
    depends_on:
      login_db:
        condition: service_healthy
  
  login_db:
    image: postgres:15-alpine
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=contrasecontrase
      - POSTGRES_DB=login
    restart: always
    volumes:
      - postgres_login_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pg -d login"]
      interval: 5s
      timeout: 10s
      retries: 2

volumes:
  postgres_login_data:
